### PR TITLE
Marked `additional_properties` as hidden

### PR DESCRIPTION
**Pull request by tshrv**
Fix for issue #72 
Marked `additional_properties` as hidden and made corresponding changes for test cases.

### CODE REVIEW

**Review by fbertsch — APPROVED** [review]
This looks good, thank you @tshrv! If you're interested in tackling a follow-up, https://github.com/mozilla/lookml-generator/issues/133 could be a good next step. There you would use JSON schemas and CI to validate the structure of some of our data files in this repository. We have examples from other repositories so it shouldn't be overly difficult.

**Comment by fbertsch** [comment]
@tshrv can you rebase this change on `upstream/main` and fix the conflicts?

**Comment by tshrv** [comment]
Hey @fbertsch, sorry I got caught up in a few things.

**Comment by fbertsch** [comment]
@tshrv no worries. Let me know if you need any help rebasing and I can try and give some directions.

**Comment by tshrv** [comment]
I see that you've merged it with main, is that it or do I have to do it?

**Comment by fbertsch** [comment]
@tshrv you'll need to rebase on main locally. There will be some conflicts you'll have to resolve, do you know how to do that?

**Comment by tshrv** [comment]
@fbertsch No but let me give it a try.

**Comment by tshrv** [comment]
@fbertsch I tried to rebase it but I'm not very proficient at using it, so did it work?

**Comment by fbertsch** [comment]
@tshrv No, unfortunately I still can't merge this PR due to conflicts with the base branch, and I can't push since it's on your fork. You'll have to do the following:
```
cd /path/to/lookml-generator
git checkout hide-additional-properties
git fetch upstream
git rebase upstream/main
git status # display conflicts
# use your favorite text editor here to fix conflicts*
vi /path/to/conflicting/file
git add /path/to/conflicting/file
git rebase --continue
git push -u origin hide-additional-properties
```

Please read this for more isntructions: https://codeinthehole.com/guides/resolving-conflicts-during-a-git-rebase/

**Comment by tshrv** [comment]
@fbertsch Please try now.

**Comment by fbertsch** [comment]
@tshrv aha, got it.

**Pull request merged**
